### ISSUE TITLE
Way for a failing suite to not kill the process?

### ISSUE THREAD

**Issue by christav** [bevry/joe#10]
I'm working on a fairly large project, and we have to split our tests across multiple files and suites to maintain our sanity.

In playing with joe, it makes it possible to do this in a variety of different ways, and that's cool, but I'm dealing with one thing that I think may be a problem: if a test fails in a suite, it kills the entire process.

I'd really like if there was some way to configure things so that if a suite fails, that suite fails but other suites can still go ahead and run, and get a consolidated list of failures at the end.

**Comment by mikeumus** [comment]
Hi @christav, I'm doing some Spring cleaning and am going to close this issue for now. Please feel free to come back to it if needed. 😃 🌻

**Comment by christav** [comment]
@mikeumus That's cool. I haven't been working in JS lately, but if I remember correctly I found a way around the issue.
