### ISSUE TITLE
Latest version of joe breaks docpad plugin tests

### ISSUE THREAD

**Issue by SteveMcArthur** [bevry/joe#19]
To get docpad plugin tests to work I need to downgrade to version 1.6 of joe and 2.4.3 of [event-emitter-grouped](https://github.com/bevry/event-emitter-grouped). See issue raised over at docpad: [issue 104](https://github.com/docpad/docpad/issues/1047)

**Comment by balupton** [comment]
Probably caused by #18 will look  into this

**Comment by balupton** [comment]
So looking at https://github.com/docpad/docpad-plugin-eco/commit/834fccc511dfb6ac304c6131acdc3e6021f8a858

It seems I fixed this in April 2017. Also seems I automated the fix. Seems the fix is merely running https://github.com/bevry/based on the affected plugins.

**Comment by balupton** [comment]
@Aglezabad ^^
